apiVersion: v1
entries:
  observo-client:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-06-17T12:06:05.35189+06:00"
    description: A Helm chart for Observo Client
    digest: 807082447f6c23a728c1500dfb8fec7279300c22b1dac07c7e52cb5dbe71b038
    name: observo-client
    type: application
    urls:
    - https://observo-inc.github.io/observo-shared/edge/helm/observo-client-0.1.0.tgz
    version: 0.1.0
generated: "2025-06-17T12:06:05.350053+06:00"
