apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observo-shared.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observo-shared.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "observo-shared.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "observo-shared.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecret.enabled }}
      imagePullSecrets:
        - name: {{ include "observo-shared.fullname" . }}-registry-secret
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: EDGE_CONFIG
              value: {{ .Values.edgeConfig | quote }}
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }} 