---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observo-node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observo-node-reader-binding
subjects:
- kind: ServiceAccount
  name: observo-client
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: observo-node-reader
  apiGroup: rbac.authorization.k8s.io 