# Default values for the application
replicaCount: 1

# Namespace configuration
namespace: test-edge

image:
  repository: observo/observo-shared
  tag: dev-feature_ob_7000_k8s_deployment_support-2025-06-14-11-19-34
  pullPolicy: IfNotPresent
  # Registry configuration
  registry: docker.io
  # Pull secret configuration
  pullSecret:
    enabled: true
    token: eyJhdXRocyI6eyI4MjI0MzQzNDY5MzkuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6eyJhdXRoIjoiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsVE1GcDNVMFpHZFZsWFZYWmlSVFZhVmpKV05Wb3dXbGxMZWxweVUwaGtXRmRWWkZGTlZWRnlZa1p3TWxkRmF6TlpWVnBzVlROT2VXVlVRalpWTW14TlZFUk5lR042WTNKVGVsSTJUa1JzYlUwd2JEWlRNVVpDWTFWT2JVNUdZM2RXVlRVd1lrVTViVXd6VG5GUFJrSnVUak5HWVZSR1ZrSlNXRUpyVWxSWmVGa3daM2RpTUZKVVdtNW9SMkpxVW5OVU1tUlBZekphY1V3eWRIaFRhbXQzV1RGb00xa3paR3hqVlhSelpXMW9jVk51Umtoak1Xd3dZbGhHYWxreU1ETlJiR2N6WlVST1YxSXhhRVJUYTBwT1ZWZGtRbG96Vm1GTE1VcEVXbGhXTUdFeFRUUk5SVFZMWTBaQ05GUXpTbmhWUlRWVlZERkdNVll6Y0ROTlJGcHVVMFpzTkZVd01EQlBSRVp1U3pOd1RWZElXWFpWTUd4SVZtcEdOVXd3VVhabGJHOHpWVlpHYlZJeWFIWlJiVTAxVGxjNWRsUXhRbmRqU0d4SVZsUkpjazVyU2pGWldGSlVWMjVXTTJOWGNFdE5SRnBEVTJwck0xTlZPVlprTTJSWFQxZHJNRTB3TVVaT2JXaDNTekphYmsxV1JsRmhSRnBhWWxSc2NGWXdVVEJMTVZaQ1QwWktNa3N6YUhaaWJrWkhVbTVTYlZsVmFITmxVM1JPWWpKb2FtUXllRFJOUjA1RVkxY3dNbHBJVG5saGF6VnFWa1Y0UlZGdWFFZGpSMHBWVDBaQ2NWcHBPVXBoUkVaT1kwVTRNRmx0Y0RWUFdGWkVUVlJHU2t3elRuWmFWR1I0V21wYVdHSXdaRFpVYTBvMFpWUmFiMk51WkcxVmVsSkNVVEJGTlUxWFNURlhWRUY0VVdwS1dVOUZaRVJUVlVwRVRUQktVRlI2Vm1GU1ZFWldaVWRXTWxJeVNtNVZSMFYyVkVoTk5XRnRjRXBYYTFreFdWVTViMk14Y0ZWTE1HaHRZWHBCZDAxcVJubFhWekUwVjFoV2NXSllSak5TU0d4V1YwVlNkVk5ITVc5WFNIQkVWMjVXZDA5V1VuaGthM1I2VGpObmQxWlZjSFpUUjI4elRETm9kbU5ZYUV4YU1GWkdXbTA1V2t0NlpIaGlTRVUwV1dzNU1tTlZOVzlOYldSUlRWVTVRazlZVG5kU1JVcEpWMnM1U0UxR1JrSlJla1p0VTFOMFZWWldRbE5qZVhSdFRsUk9kMk5FYTNKaWVUbHdXVlZTYzFkSVVuVlJWekI0WkVob1NXUXdhelJrYldSVFlrVmtNbUpHV1haTU1uQkVWRzFHTkZwV1drdGtSV2hWVkROUk5GSllTbGxsVmsweVdXMTRiVTFYU25Ca1NFNTZVakJLVVVzelNsRlRXRXB1WXpCdmQwMXRaSFZhUldzeVdsYzBlbGxWYkd0a1IwbDJXbXM1VUZsdVFsaFBTRTVDV1c1S1QyTnJTbUZWUlhBelkzcGtXazF0VGxGTU1rbDJUa2MxZGxkVGRIRlZiR1JwWTNwU2MxVnFXVFJSVmtwS1RrZGtkR0ZHV2xCU1JXeHpWVzFKTUVzelZrTmlWV1JXVGpKb2NWb3hXblZVZWtKdVl6STFjbHBFV2pCa2JWcHlUbFpPY1ZVd1ZuTlBSa3B6V1ZaWmQyTXpVa3hXYkU1YVZVWmtWMU50Wkc1WFJrVXhXVEZhV1V3d1NrSmxWbWhvVm0xb2RsRnRVWGhPUlZKSFlrUldjV1ZHVmpaU01XeFVVMWN4VkZwRk5VcGtTR2hQWkRCR1JGWkhaM1pWTUdoYVkydEdRMlJVYUZKVWEwWkNWMVpHUlZwSVozcGpWRTE0WWxkb2FGTnROVVZTUkd4VldrVk9RbFJGTlRaamVrcEpZMjFLYTJGNmFGQlZVemcwVkVVeGRtUXpaSEpqUTNSRFZHcEdTMWxzVW5KVVJWcEZVak5zY0ZScVNsbGtSa1pXVXpKb2JsTXhhR3RQUm1zeVRtcGtWVk50TldwT01uTjVWbWs1YjA1dE1VNWpXRkkyWkcxR2Qwc3hXblZoYTFKTFQxUlpjazlGZUVaVmFrNDJWakJXTkZWSE5UUldiR2hzWkRBeFNHTldTa3BQVjFZeVUxZDRkMU15ZUUxV2JIQlFaRzFvYWxwRk1USmpXRTVQVkRGQ2MyUlhTakpTUkZWNldWYzFSMlZyVmpSWFNFSklUVVZHVVZReldraE9iV013VlZjMU1FMHlNVE5pYlZGNlpGUldWbVJZVGs1aGF6VnlVMnRTVGxadGRGSlViRnBZVmxSQ2RWTjVPSGxsUjA1SVYwZHNiVXQ2UWxkTU1IQlhaVzF3UTA1NlJuRmlXRUpEVW10MGJXTlVRbnBqVmtKclNXbDNhVnBIUmpCWlYzUnNaVk5KTmtsclJsSlNWVXBDVTBkb00ySlVRbHBaVld4VVUyMVdVMlJGY0hST1Z6UjRVbnBhTVdOWFZteGhNV2d4WWpGb1dWVkhWVEZXVlZwcVdsUnNVMk5VWjNaTlZGSXpVVlZHUWxORVVqTmFhMFphVTJ0MGRsZHJiRzlrYlU1UFVWWkdhbEl5T1VoUFNHUnBWVlZzUTFGVlVrTmlNRXB1WVROR2IyRXliRWhQV0dOM1VXdEtNMUpZWkVsYU1XeExWMVZzWVZOVlJsaFdWVkpEVVZWV01WUlZTa1pTVlZKSlRXMUtUMXB0V21GV1JURlpUSHBqZDFGVVdsTmtNR3hEVWxWc1FrNHlTa2xaYkU1WlRXdGFkVnBFYUhsYWVtUkVUME4wTUdSVVFsbFNibFl6V25wYVJsZElSa2xWYkd4MVdraHdVbVZXWTNsV1dFWnBaRVJuZVUweWNGZFNWMXA2VVZabk0ySlZkM2hUYXpGaFZESk9kazlWVmxkVFYyUnZUMGN4VjFsV1pFZFNSMnN3VWtSbk9VbHBkMmxrYlZaNVl6SnNkbUpwU1RaSmFrbHBURU5LTUdWWVFteEphbTlwVWtWR1ZWRldPVXhTVm10cFRFTktiR1ZJUW5CamJVWXdZVmM1ZFVscWIzaE9lbFYzVFVSUk5FNUVTVFJtVVQwOSJ9fX0g

# Edge configuration
edgeConfig: eyJzaXRlX2lkIjo0NzUsImVkZ2VfbWFuYWdlcl91cmwiOiJESVNBQkxFRF9EQVRBUExBTkVfSU5HUkVTUyIsImZsZWV0X2lkIjoiZjg2MWNkZTYtZTQ1NC00ZjkzLTgyMWYtYWVkNmFiZWI0OTM5IiwiY29uZmlnX3ZlcnNpb25faWQiOiJiYmZhYTAyYS0wNGViLTQ1YTUtYjQwNC04Y2QxN2EwZDMxYmUiLCJhZ2VudF92ZXJzaW9uIjoiIiwicGxhdGZvcm0iOiJMSU5VWCIsImF1dGhfdG9rZW4iOiIxNjE4ODdkZTE0MTBlYTRlYTk1YjczMmNlOWIwMTAyOTBjYjBiNjU4ZDRhN2VhNjc0ZWE0NTQ4YjFhYjZkZDMwIn0=

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Additional environment variables
env: []
  # - name: ENV_VAR
  #   value: value

# Additional volume mounts
volumeMounts: []
  # - name: config-volume
  #   mountPath: /etc/config

# Additional volumes
volumes: []
  # - name: config-volume
  #   configMap:
  #     name: special-config 